BUY = "BUY"
SELL = "SELL"


class Env:
    CLIENT_ID = "CLIENT_ID"
    EMAIL_ADDRESS = "EMAIL_ADDRESS"
    EMAIL_PASSWORD = "EMAIL_PASSWORD"
    EMAIL_RECIPIENTS = "EMAIL_RECIPIENTS"
    GOOGLE_SHEET = "GOOGLE_SHEET"
    GOOGLE_SHEET_PRIVATE_KEY = "GOOGLE_SHEET_PRIVATE_KEY"
    GOOGLE_SHEET_PRIVATE_KEY_ID = "GOOGLE_SHEET_PRIVATE_KEY_ID"
    MONGO_DB = "MONGO_DB"
    MONGO_URI = "MONGO_URI"
    SERVICE_ACCOUNT = "SERVICE_ACCOUNT"
    SYSTEM = "SYSTEM"
    BACKTEST_PASSWORD = "BACKTEST_PASSWORD"
    BACKTEST_TWO_FA = "BACKTEST_TWO_FA"
    BACKTEST_USER_ID = "BACKTEST_USER_ID"


class SheetIndex:
    ENVIRON = 0
    USER = 1


class Broker:
    ZERODHA = "Zerodha"
    ANGEL_ONE = "AngelOne"
