BUY = "BUY"
SELL = "SELL"

CACHE_ENTRY_SIGNAL_DETAIL = {}
CACHE_EXIT_SIGNAL_DETAIL = {}

class Env:
    EMAIL_ADDRESS = "EMAIL_ADDRESS"
    EMAIL_PASSWORD = "EMAIL_PASSWORD"
    EMAIL_RECIPIENTS = "EMAIL_RECIPIENTS"
    MONGO_DB = "MONGO_DB"
    MONGO_URI = "MONGO_URI"
    MACHINE_OS = "MACHINE_OS"
    BACKTEST_PASSWORD = "BACKTEST_PASSWORD"
    BACKTEST_TWO_FA = "BACKTEST_TWO_FA"
    BACKTEST_USER_ID = "BACKTEST_USER_ID"
    USERS_SECRETS = "USERS_SECRETS"
    MOCK_TRADING = "MOCK_TRADING"


class Broker:
    ZERODHA = "Zerodha"
    ANGELONE = "AngelOne"
